name: END TO END Tests

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''

  pull_request:
    branches:
      - main
  schedule:
    - cron: '25 14 * * *'

jobs:
  E2E_TestWindows:
    runs-on: windows-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests on Windows Edge
        continue-on-error: true
        run: mvn test "-DbrowserName=edge" "-Dallure.results.directory=target/allure-results" "-DheadLessExecution=false" "-Dtest=${{ github.event.inputs.testsPath }}"

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Report-Edge-Windows
          path: target/allure-results


  #      - name: Publish Test Results for Windows Edge
#        continue-on-error: true
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Tests Report Windows-Edge
#          path: 'target/surefire-reports/TEST-*.xml'
#          reporter: java-junit

  E2E_TestUbuntu:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests on Ubuntu Chrome
        continue-on-error: true
        run: mvn test "-DbrowserName=chrome" "-Dallure.results.directory=target/allure-results" "-DheadLessExecution=true" "-Dtest=${{ github.event.inputs.testsPath }}"

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
            name: Allure-Report-Edge-Windows
            path: target/allure-results

#      - name: Generate Allure Report
#        continue-on-error: true
#        run: mvn allure:report
#
#      - name: Upload Allure Report as Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: Allure_Report_Ubuntu_Chrome
#          path: target/site/allure-maven-plugin/index.html

#      - name: Publish Test Results for Ubuntu Chrome
#        continue-on-error: true
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Tests Report Ubuntu Chrome
#          path: 'target/surefire-reports/TEST-*.xml'
#          reporter: java-junit
